CREATE TABLE S_BL_LOAN  (
		  AGMT_NO VARCHAR2(25) , 
		  AGMT_ID VARCHAR2(25) , 
		  ACCT_BRANCH_ID CHAR(12) , 
		  OPEN_ACCT_ORG_ID CHAR(12) , 
		  CURR_CD CHAR(3) , 
		  ITEM_CD CHAR(8) , 
		  ITEM_CD_TYPE CHAR(1) , 
		  ST_DT DATE , 
		  OPEN_ACCT_AMT NUMBER(16,2) , 
		  BALANCE NUMBER(16,2) , 
		  AVERAGE_BALANCE NUMBER(16,2) , 
		  INT_RATE NUMBER(10,6) , 
		  RATE_FLAG CHAR(1) , 
		  ACCRUAL_DAYCOUNT_BASIS CHAR(1) , 
		  DATA_DT DATE , 
		  DATA_SOURCE CHAR(1) , 
		  END_DT DATE , 
		  PREVIOUS_PAYMENT_DATE DATE , 
		  NEXT_PAYMENT_DATE DATE , 
		  PREVIOUS_REPRICE_DATE DATE , 
		  NEXT_REPRICE_DATE DATE , 
		  RATE_CHANGE_FREQUENCY INTEGER , 
		  RATE_CHANGE_FREQUENCY_UNIT CHAR(1) , 
		  PAYMENT_FRENQUENCY INTEGER , 
		  PAYMENT_FRENQUENCY_UNIT CHAR(1) , 
		  AMORTIZATION_FREQUENCY INTEGER , 
		  AMORTIZATION_FREQUENCY_UNIT CHAR(1) , 
		  PAYMENT_AMOUNT NUMBER(16,2) , 
		  PAYMENT_TYPE CHAR(4) , 
		  BALLOON_DATE DATE , 
		  BASE_FLT_PCT NUMBER(10,6) , 
		  INT_RATE_CD CHAR(4) , 
		  BASE_FLT_VALUE NUMBER(10,6) , 
		  JJ_CODE CHAR(3) , 
		  TT_CODE CHAR(3) , 
		  ACCOUNTING_PRODUCT_CODE CHAR(8) , 
		  LOAN_RATE_LEVEL CHAR(2) , 
		  GUARANTEE_TYPE CHAR(2) , 
		  BUSINESS_LINE CHAR(4) , 
		  CUSTOMER_ID VARCHAR2(30) )   



DELETE FROM CD_FDW_STRUCTURE WHERE TABLE_NAME IN ('S_BL_LOAN') AND OBJECT_TYPE='TABLE';
DELETE FROM CD_FDW_STRUCTURE WHERE TABLE_NAME='PK_S_BL_LOAN' AND OBJECT_TYPE='INDEX';

EXEC PACK_FERMAT.CREATE_TABLE('S_BL_LOAN','ADMIN','F','');
-- 标识成客制化表
UPDATE CD_FDW_STRUCTURE SET STANDARD_CUSTOM='C' WHERE TABLE_NAME IN ('S_BL_LOAN');
-- 更新DMM
EXEC PACK_DB_OBJECT.INITIALIZE_TABLE_COLUMNS('S_BL_LOAN');

-- 重建表为分区表
EXEC PACK_DDL.CHANGE_TABLE_TYPE('S_BL_LOAN','DATA');
-- 定义Policy
EXEC PACK_INSTALL.PARTITION_DEFINE_POLICIES('S_BL_LOAN');
EXEC PACK_DDL.RECREATE_TABLE('S_BL_LOAN');

-- 定义主键与建立索引
INSERT INTO CD_FDW_STRUCTURE (TABLE_NAME,TABLE_TYPE,HIST_TABLE_NAME,OBJECT_TYPE, STANDARD_CUSTOM, INIT_MODE, PARAMETER) 
VALUES ('PK_S_BL_LOAN', 'PRIMARY', 'S_BL_LOAN', 'INDEX', 'C', 'L', 'PARTITION_KEY,AGMT_NO,AGMT_ID,ITEM_CD');
CALL PACK_DDL.REBUILD_INDEX('S_BL_LOAN','PK_S_BL_LOAN');

-- 更新DMM
EXEC PACK_DB_OBJECT.INITIALIZE_TABLE_COLUMNS('S_BL_LOAN');
COMMIT;
